"""Phase 1 foundation: users, authorities, applications, application_events, documents, deadlines, appeals, audit_logs

Revision ID: 0560720502fd
Revises:
Create Date: 2026-08-23 13:19:49.346300

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0560720502fd"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authorities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column(
            "type",
            sa.Enum("CENTRAL", "STATE", name="authority_level", native_enum=False),
            nullable=False,
        ),
        sa.Column("jurisdiction", sa.String(length=300), nullable=False),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("district", sa.String(length=100), nullable=True),
        sa.Column("department", sa.String(length=300), nullable=True),
        sa.Column(
            "filing_channel",
            sa.Enum("ONLINE", "OFFLINE", "HYBRID", name="filing_channel", native_enum=False),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_authorities_name"), "authorities", ["name"], unique=False)
    op.create_index(
        "ix_authorities_state_district", "authorities", ["state", "district"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("CITIZEN", "GOVERNMENT_OFFICER", "ADMIN", name="user_role", native_enum=False),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "phone IS NOT NULL OR email IS NOT NULL", name="ck_users_phone_or_email"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone"),
    )
    op.create_table(
        "applications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("registration_number", sa.String(length=64), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("authority_id", sa.UUID(), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("original_request", sa.Text(), nullable=False),
        sa.Column("refined_request", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "VALIDATED",
                "READY_TO_FILE",
                "SUBMITTED",
                "ACKNOWLEDGED",
                "TRANSFERRED",
                "UNDER_PROCESSING",
                "RESPONSE_RECEIVED",
                "RESPONSE_ANALYSIS",
                "COMPLETED",
                "NO_RESPONSE",
                "INCOMPLETE_RESPONSE",
                "FIRST_APPEAL_ELIGIBLE",
                "FIRST_APPEAL_FILED",
                "SECOND_APPEAL_ELIGIBLE",
                name="application_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("response_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("response_received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["authority_id"], ["authorities.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("registration_number"),
    )
    op.create_index(
        op.f("ix_applications_authority_id"), "applications", ["authority_id"], unique=False
    )
    op.create_index("ix_applications_status", "applications", ["status"], unique=False)
    op.create_index(op.f("ix_applications_user_id"), "applications", ["user_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_logs_entity", "audit_logs", ["entity_type", "entity_id"], unique=False
    )
    op.create_table(
        "appeals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column(
            "appeal_type",
            sa.Enum("FIRST", "SECOND", name="appeal_type", native_enum=False),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "FILED", "WITHDRAWN", name="appeal_status", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_appeals_application_id"), "appeals", ["application_id"], unique=False)
    op.create_table(
        "application_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_events_application_id"),
        "application_events",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        "ix_application_events_application_timestamp",
        "application_events",
        ["application_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_events_event_type"), "application_events", ["event_type"], unique=False
    )
    op.create_table(
        "deadlines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column(
            "deadline_type",
            sa.Enum(
                "RESPONSE",
                "TRANSFER",
                "LIFE_AND_LIBERTY",
                "FIRST_APPEAL",
                "SECOND_APPEAL",
                name="deadline_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "MET", "MISSED", "CANCELLED", name="deadline_status", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deadlines_application_id"), "deadlines", ["application_id"], unique=False
    )
    op.create_index(
        "ix_deadlines_application_status", "deadlines", ["application_id", "status"], unique=False
    )
    op.create_index("ix_deadlines_due_at", "deadlines", ["due_at"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "APPLICATION",
                "RESPONSE",
                "APPEAL",
                "PAYMENT_PROOF",
                "IDENTITY_PROOF",
                "OTHER",
                name="document_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("storage_reference", sa.String(length=500), nullable=False),
        sa.Column("filename", sa.String(length=300), nullable=False),
        sa.Column("content_type", sa.String(length=150), nullable=False),
        sa.Column("hash", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_documents_application_id"), "documents", ["application_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_application_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index("ix_deadlines_due_at", table_name="deadlines")
    op.drop_index("ix_deadlines_application_status", table_name="deadlines")
    op.drop_index(op.f("ix_deadlines_application_id"), table_name="deadlines")
    op.drop_table("deadlines")
    op.drop_index(op.f("ix_application_events_event_type"), table_name="application_events")
    op.drop_index("ix_application_events_application_timestamp", table_name="application_events")
    op.drop_index(op.f("ix_application_events_application_id"), table_name="application_events")
    op.drop_table("application_events")
    op.drop_index(op.f("ix_appeals_application_id"), table_name="appeals")
    op.drop_table("appeals")
    op.drop_index("ix_audit_logs_entity", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_applications_user_id"), table_name="applications")
    op.drop_index("ix_applications_status", table_name="applications")
    op.drop_index(op.f("ix_applications_authority_id"), table_name="applications")
    op.drop_table("applications")
    op.drop_table("users")
    op.drop_index("ix_authorities_state_district", table_name="authorities")
    op.drop_index(op.f("ix_authorities_name"), table_name="authorities")
    op.drop_table("authorities")
    # ### end Alembic commands ###
