"""Add information_items ledger

Revision ID: 1a94ea965ac6
Revises: 0560720502fd
Create Date: 2026-08-23 19:13:42.037122

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a94ea965ac6"
down_revision: str | None = "0560720502fd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "information_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ANSWERED",
                "PARTIALLY_ANSWERED",
                "NOT_ANSWERED",
                "POTENTIALLY_DEFICIENT",
                name="information_item_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("evidence_excerpt", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.CheckConstraint(
            "status IN ('PENDING', 'ANSWERED', 'PARTIALLY_ANSWERED', 'NOT_ANSWERED', "
            "'POTENTIALLY_DEFICIENT')",
            name="information_item_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_information_items_application_id"),
        "information_items",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        "ix_information_items_application_sequence",
        "information_items",
        ["application_id", "sequence"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_information_items_application_sequence", table_name="information_items")
    op.drop_index(op.f("ix_information_items_application_id"), table_name="information_items")
    op.drop_table("information_items")
    # ### end Alembic commands ###
