"""Add unique constraint on appeals application_id and appeal_type

Revision ID: 8ad35c1baa23
Revises: 1a94ea965ac6
Create Date: 2026-08-23 20:56:37.706405

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ad35c1baa23"
down_revision: str | None = "1a94ea965ac6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_appeals_application_appeal_type", "appeals", ["application_id", "appeal_type"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_appeals_application_appeal_type", "appeals", type_="unique")
    # ### end Alembic commands ###
